### ISSUE TITLE
What versions of mmsegmentation and mmcv-full are you using?

### ISSUE THREAD

**Issue by haikunzhang95** [201210302/DeSRA_execution#1]

**Comment by 201210302** [comment]
I used 
python 3.10.2
torch 2.0.1+cu117
mmseg version 1.2.2
mmcv  2.0.0

**Comment by haikunzhang95** [comment]
> I used python 3.10.2 torch 2.0.1+cu117 mmseg version 1.2.2 mmcv 2.0.0

According to the above dependencies, can your artifact_detection.py run correctly? I'm currently having a lot of problems.

**Comment by haikunzhang95** [comment]
> I used python 3.10.2 torch 2.0.1+cu117 mmseg version 1.2.2 mmcv 2.0.0

Follow your version, I encounter errors like:
**Error MultiScaleFlipAug.__init__() got an unexpected keyword argument 'img_scale' ILSVRC2012_val_00000273.png**
Do you had the same errors?

**Comment by 201210302** [comment]
@haikunzhang95 Using artifact_detection.py in my github,  I got Final_Artifact_Map. I recommend delete mmsegmentaion and DeSRA and reinstall. And I will update Readme.md soon
