### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by haikunzhang95** [201210302/DeSRA_execution#2]
I used:
**segformer_mit-b5_640x640_160k_ade20k.py**
but encounter error:
**FileNotFoundError: [Errno 2] No such file or directory: '*/projects/mmsegmentation/configs/segformer/./segformer_mit-**b0**_512x512_160k_ade20k.py'**
Why **b0**？

**Comment by cncloudli** [comment]
这项目有bug。重新读了一遍这个py文件才发现的。第一行里有个base参数，导向了另外一个地址。但问题是找不到这另外一个文件应该在哪儿下载，看了segformer提供的ADE20K里也没有和这个重名的。不知道是不是因为原论文的作者发布的配置文件版本和segformer里面的不一样
