### ISSUE TITLE
Errors in configs

### ISSUE THREAD

**Issue by haikunzhang95** [201210302/DeSRA_execution#3]
I countered errors like：
**Error `scale` and`scale_factor` can not both be `None`**
My guess is that the config used by the author of the paper does not match the latest version of mmsegmentation. Can you provide the **configs** folder you use?

**Comment by haikunzhang95** [comment]
> I countered errors like： **Error `scale` and`scale_factor` can not both be `None`** My guess is that the config used by the author of the paper does not match the latest version of mmsegmentation. Can you provide the **configs** folder you use?

I know.
Change test_pipeline in segformer_mit-b5_640x640_160k_ade20k.py to: 
**test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=(2048, 640), keep_ratio=True),
    # add loading annotation after ``Resize`` because ground truth
    # does not need to do resize data transform
    dict(type='LoadAnnotations', reduce_zero_label=True),
    dict(type='PackSegInputs')
]**

**Comment by 201210302** [comment]
@haikunzhang95 I upload the file I used
